export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';
export const FETCH_ALL_GAMES = 'FETCH_ALL_GAMES';
export const FETCH_ONE_GAME = 'FETCH_ONE_GAME';
export const SUBMIT_FORM = 'SUBMIT_FORM';